#!/bin/bash

# Update
sudo pacman -Syyu --noconfirm || exit 1

# Install all packages
sudo pacman -S --needed --noconfirm $(sed '1d' pack.csv | awk -F "," '{print $1}' | xargs) || exit 1

# enable services
sudo systemctl enable tlp
sudo systemctl enable bluetooth.service

# set touchpad
sudo cp -v -r etc /

# copy all configs
cp -v -r config ~/.config
cp -v -r dots/{.bash_profile,.xinitrc,.xprofile,.scripts} ~/

# make directories
mkdir -v -p ~/Pictures/Screenshots
mkdir -v -p ~/Drives/{1..5}

# copy wallpapers
cp -v -r wallpapers ~/Pictures/Wallpapers

# install plugins for neovim
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +PlugInstall +qall
