#!/bin/bash

# i3 config
cp -v ~/.config/i3/config config/i3/config
cp -v ~/.config/i3blocks/config config/i3blocks/config

# i3blocks scripts
cp -v ~/.config/i3blocks/scripts/battery.sh config/i3blocks/scripts/battery.sh
cp -v ~/.config/i3blocks/scripts/brightness.sh config/i3blocks/scripts/brightness.sh
cp -v ~/.config/i3blocks/scripts/capslock.sh config/i3blocks/scripts/capslock.sh
cp -v ~/.config/i3blocks/scripts/mic.sh config/i3blocks/scripts/mic.sh
cp -v ~/.config/i3blocks/scripts/time.sh config/i3blocks/scripts/time.sh
cp -v ~/.config/i3blocks/scripts/volume.sh config/i3blocks/scripts/volume.sh
cp -v ~/.config/i3blocks/scripts/wifi.sh config/i3blocks/scripts/wifi.sh

# scripts
cp -v ~/.scripts/dpass scripts/dpass
cp -v ~/.scripts/mountdrv scripts/mountdrv
cp -v ~/.scripts/umountdrv scripts/umountdrv

# nvim scripts
cp -v ~/.config/nvim/init.vim config/nvim/init.vim

# xresources
cp -v ~/.Xresources config/.Xresources

# kitty
cp -v ~/.config/kitty/kitty.conf config/kitty.conf
