#!/usr/bin/bash
cp ~/.bash_profile bash_profile.sh ;
cp ~/.bashrc bashrc.sh ;
cp ~/.xinitrc xinitrc.sh ;
cp ~/.xprofile xprofile.sh ;
cp ~/.Xresources Xresources ;
cp ~/.config/fontconfig/fonts.conf fonts.conf ;
cp ~/.config/i3/config i3-config.sh ;
cp ~/.config/i3blocks/config i3blocks-config.sh ;
cp ~/.config/nvim/init.vim init.vim ;
cp /etc/X11/xorg.conf.d/30-touchpad.conf touchpad.conf ;
