#!/bin/bash

cp -v ~/.config/i3/config config/i3/config
cp -v ~/.config/i3blocks/config config/i3blocks/config
cp -v ~/.config/kitty/kitty.conf config/kitty/kitty.conf
cp -v ~/.config/nvim/init.vim config/nvim/init.vim
cp -v ~/.config/background.jpg config/background.jpg
