#!/bin/bash

cp -v ~/.config/i3/config config/i3/config
cp -v ~/.config/i3blocks/config config/i3blocks/config

cp -v ~/.config/i3blocks/scripts/battery.sh config/i3blocks/scripts/battery.sh
cp -v ~/.config/i3blocks/scripts/brightness.sh config/i3blocks/scripts/brightness.sh
cp -v ~/.config/i3blocks/scripts/capslock.sh config/i3blocks/scripts/capslock.sh
cp -v ~/.config/i3blocks/scripts/mic.sh config/i3blocks/scripts/mic.sh
cp -v ~/.config/i3blocks/scripts/time.sh config/i3blocks/scripts/time.sh
cp -v ~/.config/i3blocks/scripts/volume.sh config/i3blocks/scripts/volume.sh
cp -v ~/.config/i3blocks/scripts/wifi.sh config/i3blocks/scripts/wifi.sh

cp -v ~/.config/nvim/init.vim config/nvim/init.vim

cp -v ~/.Xresources config/.Xresources

cp -v ~/.config/kitty/kitty.conf config/kitty.conf
