#!/bin/bash
# get mounted drive
mounted=$(lsblk -lp | grep "Drives" | awk '{print $1, "(" $4 ")"}')
[[ "$mounted" = "" ]] && exit 1

# chose drive
chosen=$(echo "$mounted" | dmenu -fn 'JetBrainsMono:style=Regular:pixelsize=14' -nb '#282828' -nf '#ebdbb2' -sf '#ebdbb2' -sb '#504945' -i -p "Unmount which drive?" | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1

sudo -A umount $chosen
